### ISSUE TITLE
bugfix argument not accepted

### ISSUE THREAD

**Issue by james-v-wong** [RittmanMead/obi-concurrent-develop#2] opened 2017-05-08 19:04 UTC
The 'bugfix' choice is not in the action list.

**Comment by mineshpatel1** [comment] 2017-05-09 07:54
Duplicate of #1

**Comment by mineshpatel1** [comment] 2017-05-09 08:07
This has been fixed as of v1.01 in `obi-merge-git.py`, see #1 for details. For the SVN version, the workflow is slightly different (because of how SVN works), use `startReleaseHotfix` and `finishReleaseHotfix` to achieve the same goal of merging from a release back into develop.

**Closed as completed by mineshpatel1** 2017-05-09 08:07 UTC
Labels: duplicate

**Comment by james-v-wong** [comment] 2017-05-09 12:41
Sorry my mistake.
